### ISSUE TITLE
Category Changes

### ISSUE THREAD

**Issue by iconza98** [tlenhart/ProvoDashboard#12]
Alter variables in url.py and views.py to make changes for categories.

**Comment by tlenhart** [comment]
I have inserted the images from the design student's mockup in base.html. (As of right now I haven't used the images from Provo's website.)
It should be ready for you to change the pages. The urls on the links will need to be changed still. (Right now they are just pointing to the old pages so that the site doesn't break because the pages don't exist.)

**Comment by iconza98** [comment]
I made the changes, thanks for the image swap.
